name: Code Quality Check

on:
  pull_request:
    branches:
      - main

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # Install dependencies inside the frontend directory
      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

      # Run Prettier check inside the frontend directory
      - name: Run Prettier
        run: npx prettier . --check
        working-directory: ./frontend