name: Code Quality Check

on:
  pull_request:
    branches:
      - main

jobs:
  prettier-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run Prettier
        run: cd frontend && npm run prettier-check
