name: Code Quality Check

on:
  pull_request:
    branches:
      - main

jobs:
  prettier-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend  # Specify the working directory

      - name: Run Prettier
        run: npm run prettier-check
        working-directory: ./frontend  # Specify the working directory